# Generated by Django 5.2 on 2025-05-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="введите категорию",
                        max_length=150,
                        verbose_name="категория",
                    ),
                ),
                (
                    "discription",
                    models.TextField(
                        help_text="опишите категорию", verbose_name="описание категории"
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="введите наименование продукта",
                        max_length=150,
                        verbose_name="наименование продукта",
                    ),
                ),
                (
                    "discription",
                    models.TextField(
                        help_text="опишите продукт", verbose_name="описание продукта"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="загрузите изображение продукта",
                        null=True,
                        upload_to="images/",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="введите категорию продукта",
                        max_length=150,
                        verbose_name="категория",
                    ),
                ),
                ("price", models.FloatField(default=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "ordering": ["category"],
            },
        ),
    ]
